blog/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('category/<str:slug>/', views.category_page),
    path('<int:pk>/new_comment/', views.new_comment),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('', views.PostList.as_view()),
    
]

blog2/urls.py
from django.urls import include, path
from . import views

app_name = 'blog2'

urlpatterns = [
    path('search/<str:q>/', views.PostSearch.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view(), name='update_post'),
    path('create_post/', views.PostCreate.as_view(), name='create_post'),
    path('category/<str:slug>/', views.category_page, name='category'),
    path('<int:pk>/new_comment/', views.new_comment),
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('', views.PostList.as_view(), name='post_list'),
]

do_it_django_prj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('blog2/', include('blog2.urls')),
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')), #마크다운 적용
    path('accounts/', include('allauth.urls')), #회원가입 적용
    path('', include('single_pages.urls')), #싱글페이지 앱 url 지정 /대문페이지
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #미디어url 지정
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog2/models.py
from django.db import models
from django.contrib.auth.models import User #유저 추가
from markdownx.models import MarkdownxField #마크다운 적용
from markdownx.utils import markdown #마크다운 문법적용
import os

class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=200, unique=True, allow_unicode=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f'/blog2/category/{self.slug}/'    

    class Meta:
        verbose_name_plural = "Categories"

class Post(models.Model):
    title = models.CharField(max_length=30) #제목(글,길이30)
    hook_text = models.CharField(max_length=100, blank=True) #요약문필드
    content = MarkdownxField() #내용(글,무제한)
    
    head_image = models.ImageField(upload_to='blog2/images/%Y/%m/%d/', blank=True) #블로그 밑에 이미지/연월일까지 내려간 위치에서 저장/필수항목 아님
    file_upload= models.FileField(upload_to='blog2/images/%Y/%m/%d/', blank=True) #업로드 필드

    created_at = models.DateTimeField(auto_now_add=True) #작성일시(자동수정)
    updated_at = models.DateTimeField(auto_now=True) #시간 자동 업뎃
    
    author = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='blog2_posts') #작성자정보 담름(?) 외래키

    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL, related_name='blog2_posts') #카테고리
    
    
    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}' #pk=번호, 제목 :: 외래키

    def get_absolute_url(self):
        return f'/blog2/{self.pk}/' #글 상페 url 설정
        
    def get_file_name(self):
        return os.path.basename(self.file_upload.name) #다운로드 파일 이름 나타냄

    def get_file_ext(self):
        return self.get_file_name().split('.')[-1] #다운로드 확장자 나타냄
    
    def get_content_markdown(self):
        return markdown(self.content)
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")

    def __str__(self):
        return f'{self.author}::{self.content}'
    
    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f'https://doitdjango.com/avatar/id/1503/fd7b91377dd76b87/svg/{ self.author.username }.png'

blog2/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

blog2/views.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin #로그인할때만 정상 페이지
from django.shortcuts import get_object_or_404
from .models import Post, Category, Comment
from .forms import CommentForm
from django.core.exceptions import PermissionDenied #글작성자만 수정가능

class PostList(ListView):
    model = Post
    ordering = '-pk' #최근 목록순으로 보기

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
            
        return context

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['no_category_post_count'] = Post.objects.filter(category=None).count()
        context['comment_form'] = CommentForm
            
        return context

def category_page(request, slug): #카테고리
    if slug == 'no_category':
        category = '미분류'
        post_list = Post.objects.filter(category=None)
    else:
        category = Category.objects.get(slug=slug)
        post_list = Post.objects.filter(category=category)

    return render(
        request,
        'blog2/post_list.html',
        {
            'post_list': post_list,
            'categories': Category.objects.all(),
            'no_category_post_count': Post.objects.filter(category=None).count(),
            'category': category,
        
        }
    )

class PostCreate(LoginRequiredMixin, CreateView): #글작성 폼
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']


    def form_valid(self, form):
        current_user = self.request.user #웹사이트 방문자
        if current_user.is_authenticated: #로그인 유무 확인
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
                return redirect('/blog2/')
        
def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST) 
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class PostUpdate(LoginRequiredMixin, UpdateView): #글수정
    model = Post
    fields = ['title', 'hook_text', 'content', 'head_image', 'file_upload', 'category']
    
    template_name = 'blog2/post_update_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied
        

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    template_name = 'blog2/comment_form.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied
    
    
class PostSearch(PostList):
    paginate_by = None

    def get_queryset(self):
        q = self.kwargs['q']
        post_list = Post.objects.filter(
            Q(title__contains=q)
        ).distinct()
        return post_list

    def get_context_data(self, **kwargs):
        context = super(PostSearch, self).get_context_data()
        q = self.kwargs['q']
        context['search_info'] = f'Search: {q} ({self.get_queryset().count()})'

        return context


# Create your views here.

blog2/templates/blog2/base.html
<!DOCTYPE html>
{% load static %}
<html>


<head>
    <title>{% block head_title %} KYCLUB {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog2/bootstrap/bootstrap.min.css' %}" media="screen">
        
    <script src="https://kit.fontawesome.com/2d8ffc394d.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="wrap"></div>
        {% include 'blog2/navbar.html' %}    
                
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-4">
                    <h1 class="display-5">활동</h1>
                    <p class="display-6 fs-4 lead mb-0">~ 활동 내역은 여기에 ~</p>
                </div>
            </div>
        </header>

        <!-- Page content-->
        <div class="container my-3">
            <div class="row">
                <!--Blog entries-->
                <div class="col-lg-8" id="main-area">
                        {% block main_area %}
                        {% endblock %}
                </div>
                
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header display-6 fs-6">Search</div>
                            <div class="card-body">
                                <div class="input-group">
                                    <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" id="search-input" />
                                    <button class="btn btn-primary" id="button-search" type="button" onclick="searchPost();">Go!</button>
                                </div>
                            </div>
                        </div>

                    <!-- Categories widget-->
                    <div class="card mb-4" id="categories-card">
                        <div class="card-header display-6 fs-6">Categories</div>
                            <div class="card-body">
                                <div class="row">
                                    
                                        {% for category in categories %}
                                            <li>
                                                <a href="{{ category.get_absolute_url }}">{{ category }} ({{ category.post_set.count }})</a>
                                            </li>
                                        {% endfor %}
                                        <li>
                                            <a href="/blog2/category/no_category/">미분류 ({{ no_category_post_count }})</a>
                                        </li>
                                    

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

                
        <script>
            function searchPost(){
                let searchValue = document.getElementById('search-input').value.trim();
                if (searchValue.length > 1){
                    location.href="/blog2/search/" + searchValue + "/";
                }
                else{
                    alert('검색어('+ searchValue +')가 너무 짧습니다.');
                }
            };
                    
            document.getElementById('search-input').addEventListener('keyup', function(event)
            {
                if(event.key === 'Enter'){
                    searchPost();
                }
            });
        </script>            
                <!-- Footer-->
        {% include 'blog2/footer.html' %}
                
                <!--부트 자바 jsDelivr -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
                <!--부트 자바 jsDelivr 끝-->
    </div>
</body>
</html>

blog2/templates/blog2/base_full_width.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <title>{% block head_title %} 총동아리연합회 {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog2/bootstrap/bootstrap.min.css' %}" media="screen">
        
    <script src="https://kit.fontawesome.com/2d8ffc394d.js" crossorigin="anonymous"></script>
</head>
<body>
    <div class="wrap">
        {% include 'blog2/navbar.html' %}    
            
        <!-- Page header with logo and tagline-->
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="display-5">활동</h1>
                    <p class="lead mb-0">~ 활동은 여기에 업로드 ~</p>
                </div>
            </div>
        </header>

        <!-- Page content-->
        <div class="container my-3">
            <div class="row">
                <!--Blog entries-->
                <div class="col-12 " id="main-area">
                    {% block main_area %}
                    {% endblock %}
                </div>  
            </div>
        </div>
        <!-- Footer-->
        {% include 'blog2/footer.html' %}
                
                <!--부트 자바 jsDelivr -->
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
                <!--부트 자바 jsDelivr 끝-->
    </div>
</body>
</html>

blog2/templates/blog2/comment_form.html
{% extends 'blog/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Comment - Blog{% endblock %}

{% block main_area %}
    <h1>Edit Comment</h1>
    <hr/>
    <form method="post" id="comment-form">{% csrf_token %}
        {{ form | crispy }}
        <br/>
        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
{% endblock %}

blog2/templates/blog2/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">
            CGH &copy; 건양대 총동아리연합회
        </p>
    </div>
</footer>

blog2/templates/blog2/navbar.html
{% load socialaccount %} <!--로그인 버튼 활성화-->

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand display-6 fs-5 fw-bold color-contrast-dark" href="/">건양대 총동아리연합회&nbsp&nbsp&nbsp</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link display-6 fs-6" aria-current="page" href="/">총동아리연합회&nbsp&nbsp</a>
          </li>
          <li class="nav-item">
            
            <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle display-6 fs-6" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    동아리 소개&nbsp&nbsp
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/about_me/">메디컬캠퍼스</a></li>
                    <li><a class="dropdown-item" href="/about_me2/">창의융합캠퍼스</a></li>
                  </ul>
                </li>
              </ul>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link display-6 fs-6" href="/blog/">자료실&nbsp&nbsp</a>
          </li>
          <li class="nav-item">
            <a class="nav-link display-6 fs-6" href="/blog2/">활동</a>
          </li>
        </ul>

        <ul class="navbar-nav">  <!--로그인 모달 팝업 모션 추가-->
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                        </a>
                        <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="/accounts/logout/">Log Out</a></li>
                        </ul>
                    </li>
                {% else %}
                    <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#loginModal">Log In</a> 
                {% endif %}
            </li>
        </ul>

      </div>
    </div>
  </nav> 

  <!-- 로그인 모달 -->
    <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
            <h1 class="modal-title fs-5" id="loginModalLabel"><i class="fa-solid fa-right-to-bracket"></i>&nbsp Login</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <!--구글 아이디 로그인/이메일 로그인/이메일 회원가입-->
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-6">
                        <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="{% provider_login_url 'google' %}" style="width: 100%"><i class="fa-brands fa-google"></i>&nbsp&nbsp Log in with Google </a>
                        <a type="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/login/" style="width: 100%"><i class="fa-solid fa-envelope"></i>&nbsp&nbsp Log in with E-mail</a>
                    </div>
                    <div class="col-md-6">
                        <a type="button" class="btn btn-outline-dark btn-block btn-sm" href="/accounts/signup/" style="width: 100%"><i class="fa-solid fa-envelope"></i>&nbsp&nbsp Sign Up with E-mail</a>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            
            </div>
        </div>
        </div>
    </div>

blog2/templates/blog2/post_detail.html
{% extends 'blog2/base.html' %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ post.title }} - Blog
{% endblock %}

{% block main_area %}
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-info btn-sm float-right" href="/blog2/update_post/{{ post.pk }}/" role="button"><i class="fas fa-pen"></i>  Edit Post</a>
    </div>

    <div id="post-area"> 
        <!-- Post categories-->
        {% if post.category %}
            <span class="badge bg-secondary mb-2">{{ post.category }}</span>
        {% else %}
            <span class="badge bg-secondary mb-2">미분류</span>
        {% endif %}

        <!--Title-->
        <p class="display-6">{{ post.title }}</p>
        <div class="text-muted fst-italic mb-2">Posted on {{ post.created_at}}</div>
        <!--<h5 class="text-muted">{{ post.hook_text }}</h5>-->

        <!-- Author -->
        <p class="lead">
            by <a href="#">{{ post.author | upper }}</a> 
        </p>
                        
        {% if user.is_authenticated and user == post.author %}
       
        {% endif %}
        
        <hr>
        <!-- Preview image -->
        <!--{% if post.head_image %}
            <img class="img-fluid rounded" src="{{ post.head_image.url }}" alt="{{ post.title }} head_image">
        {% else %}
            <img class="img-fluid rounded" src="https://picsum.photos/seed/{{ post.id }}/800/200" alt="random_image">
        {% endif %}
            <hr> -->

        <!-- Post content-->
        <p>{{ post.get_content_markdown | safe }}</p>
                         
        {% if post.file_upload %} <!--파일 다운로드-->
            <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>

                <!--다운로드시 확장자명-->
                {% if post.get_file_ext == 'csv' %}
                    <i class="fa-solid fa-file-csv">&nbsp;</i>

                {% elif post.get_file_ext == 'xlsx' or post.get_file_ext == 'xls' %}
                    <i class="fa-solid fa-file-excel">&nbsp;</i>

                {% elif post.get_file_ext == 'docx' or post.get_file_ext == 'doc' %}
                    <i class="fa-solid fa-file-word">&nbsp;</i>

                {% else %}
                    <i class="fa-solid fa-file">&nbsp;</i>
                {% endif %}

                {{ post.get_file_name }}

            </a>
        {% endif %}

        <hr>
    </div>
    
    
    <div id="comment-area">
        <!-- Comments Form -->
        <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
                {% if user.is_authenticated %}
                    <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ comment_form | crispy }}
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                {% else %}
                    <a role="button" class="btn btn-outline-secondary" href="#" data-toggle="modal" data-target="#loginModal" style="width: 100%">로그인 후 입력하세요</a>
                {% endif %}
            </div>
        </div>

        {% if post.comment_set.exists %}
        {% for comment in post.comment_set.iterator %}
            <!-- Single Comment -->
            <div class="media mb-4" id="comment-{{ comment.pk }}">

                <div class="media-body">
                    {% if user.is_authenticated and comment.author == user %}
                        <div class="float-right d-grid gap-2 d-md-flex justify-content-md-end">
                            <a role="button"
                                class="btn btn-sm btn-info"
                                id="comment-{{ comment.pk }}-update-btn"
                                href="/blog2/update_comment/{{ comment.pk }}/">
                                edit
                            </a>
                            <form action="/blog2/delete_comment/{{ comment.pk }}/" method="POST" class="d-inline-block">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Are you sure you want to delete this comment?')">delete</button>
                            </form>
                        </div>
                    {% endif %}
                    <h5 class="mt-0">
                        {{ comment.author.username }}
                        &nbsp;&nbsp;<small class="text-muted">{{ comment.created_at }}</small>
                    </h5>
                    <p>{{ comment.content | linebreaks }}</p>
                    {% if comment.created_at != comment.modified_at %}
                        <p class="text-muted float-right"><small>Updated: {{ comment.modified_at }}</small></p>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        {% endif %}
    </div>
{% endblock %}

blog2/templates/blog2/post_form.html
{% extends 'blog2/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Create Post - Blog{% endblock %}

{% block main_area %}
    <h1>Create New Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}

            {{ form | crispy }}

        <button type="submit" class="btn btn-primary float-right">Submit</button>
    </form>
    {{ form.media }}
{% endblock %}

blog2/templates/blog2/post_list.html
{% extends 'blog2/base.html' %}

{% block main_area %}


    {% if user.is_authenticated %}
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a class="btn btn-info btn-sm ml-auto" href="/blog2/create_post/" role="button"><i class="fas fa-pen"></i>&nbsp;&nbsp;New Post</a>
            </div>
    {% endif %}

    <h1>
        {% if search_info %}<small class="text-muted">{{ search_info }}</small>{% endif %}
        {% if category %}<span class="display-6 fw-bold">{{ category }}</span>{% endif %}     
    </h1>

    {% if post_list.exists %}
        {% for p in post_list %}         
            <!-- Blog Post-->
            <div class="card mb-4" id="post-{{ p.pk }}">
                <div class="card-body">
                    {% if p.category %}
                        <span class="badge bg-secondary mb-2">{{ p.category }}</span>
                    {% else %}
                        <span class="badge bg-secondary mb-2">미분류</span>
                    {% endif %}
                    <div class="d-flex justify-content-between align-items-center">
                        <h2 class="display-6 fs-3">{{ p.title }}</h2>
                        <a href="{{ p.get_absolute_url }}" class="btn btn-outline-primary ">Read more →</a>
                    </div>
                    <!--<p class="d-inline-block">{{ p.get_content_markdown | truncatewords_html:45 | safe }}</p> -미리보기 45자 자르기-->
                    <!--<h5 class="text-muted">{{ p.hook_text }}</h5>-->
                </div>
                <div class="card-footer text-muted">
                    Posted on {{ p.created_at }} by
                    <a href="#">{{ p.author | upper }}</a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <h3>아직 게시물이 없습니다.</h3>
    {% endif %}
         
    {% if is_paginated %}
    <nav aria-label="Pagination">
        <hr class="my-4" />
        <ul class="pagination justify-content-center my-4">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Previous</a>
                </li>
            {% endif %}

            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="page-item active">
                        <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}


{% endblock %}

blog2/templates/blog2/post_update_form.html
{% extends 'blog2/base_full_width.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Edit Post - Blog{% endblock %}

{% block main_area %}
    <h1>Edit Post</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
       
            {{ form | crispy }}
      
        <button type="submit" class="btn btn-primary float-right">Submit</button>
        <button type="button" class="btn btn-danger float-right" data-toggle="modal" data-target="#deletePostModal">Delete</button>
    </form>
    {{ form.media }}
{% endblock %}